stages:
  data_preprocessing:
    cmd: python stages/data_preprocessing.py 
    deps:
      - stages/data_preprocessing.py
    params:
      - base
      - form_time_series
    outs:
      - data/train_time_series_dataset.parquet
      - data/test_time_series_dataset.parquet
      - data/train_samples_labels.parquet
      - data/test_samples_labels.parquet
