base:
  samplings:
    - train
    - test


retrivals:
  models:
    - MostPopular
    - NewItemsLastNDays
    - LastListenRecommender
    - ALS
    - BM25
    - ItemKNN
    - BPR
    - RandomWalkWithRestart
    - KMeansEmbedding
